# Generated by Django 6.0.4 on 2026-08-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safebooks', '0031_adminaccount_two_factor_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='closure_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='client',
            name='closure_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
