"""
Django settings for safebooks project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_$!o_%6#ns^5&q*ipft8vfe^1@ht%uf8z*9()sy$f%fe7wjgq6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'safebooks.apps.SafebooksConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'safebooks.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'safebooks.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

def _env_bool(name: str, default: str = "0") -> bool:
    return str(os.getenv(name, default)).strip().lower() in {"1", "true", "yes", "on"}


def _env_int(name: str, default: str = "0") -> int:
    raw_value = os.getenv(name, default)
    try:
        return int(str(raw_value).strip())
    except (TypeError, ValueError):
        return int(default)


def _first_env(*keys: str, default: str = "") -> str:
    for key in keys:
        value = os.getenv(key)
        if value is not None and str(value).strip() != "":
            return str(value).strip()
    return default


USE_POSTGRESQL = _env_bool("SAFEBOOKS_USE_POSTGRESQL", "0")

if USE_POSTGRESQL:
    postgres_db_config = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": _first_env("SAFEBOOKS_DB_NAME", "POSTGRES_DB", default="safebooks_db"),
        "USER": _first_env("SAFEBOOKS_DB_USER", "POSTGRES_USER", default=""),
        "PASSWORD": _first_env("SAFEBOOKS_DB_PASSWORD", "POSTGRES_PASSWORD", default=""),
        "HOST": _first_env("SAFEBOOKS_DB_HOST", "POSTGRES_HOST", default="localhost"),
        "PORT": _first_env("SAFEBOOKS_DB_PORT", "POSTGRES_PORT", default="5432"),
    }

    sslmode = _first_env("SAFEBOOKS_DB_SSLMODE", "POSTGRES_SSLMODE", default="")
    if sslmode:
        postgres_db_config["OPTIONS"] = {"sslmode": sslmode}

    DATABASES = {"default": postgres_db_config}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files setup
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email delivery (defaults to console backend for development).
EMAIL_HOST = _first_env("SAFEBOOKS_EMAIL_HOST", "EMAIL_HOST", default="")
EMAIL_BACKEND = _first_env(
    "SAFEBOOKS_EMAIL_BACKEND",
    "EMAIL_BACKEND",
    default="",
)
if not EMAIL_BACKEND:
    if EMAIL_HOST:
        EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    else:
        EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

DEFAULT_FROM_EMAIL = _first_env(
    "SAFEBOOKS_DEFAULT_FROM_EMAIL",
    "DEFAULT_FROM_EMAIL",
    default="SafeBooks <no-reply@safebooks.local>",
)
EMAIL_PORT = _env_int("SAFEBOOKS_EMAIL_PORT", "587")
EMAIL_HOST_USER = _first_env("SAFEBOOKS_EMAIL_HOST_USER", "EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = _first_env("SAFEBOOKS_EMAIL_HOST_PASSWORD", "EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = _env_bool("SAFEBOOKS_EMAIL_USE_TLS", "1")
EMAIL_USE_SSL = _env_bool("SAFEBOOKS_EMAIL_USE_SSL", "0")
SAFEBOOKS_CLIENT_RECORD_EMAILS_ENABLED = _env_bool("SAFEBOOKS_CLIENT_RECORD_EMAILS_ENABLED", "1")
SAFEBOOKS_APPROVAL_DECISION_EMAILS_ENABLED = _env_bool("SAFEBOOKS_APPROVAL_DECISION_EMAILS_ENABLED", "1")

# Temporary remote-beta feedback. Keep the real recipient in environment
# configuration so the feature can be disabled or redirected without code edits.
SAFEBOOKS_FEEDBACK_ENABLED = _env_bool("SAFEBOOKS_FEEDBACK_ENABLED", "0")
SAFEBOOKS_FEEDBACK_RECIPIENT_EMAIL = _first_env(
    "SAFEBOOKS_FEEDBACK_RECIPIENT_EMAIL",
    default="",
)
SAFEBOOKS_FEEDBACK_EMAIL_TIMEOUT_SECONDS = _env_int(
    "SAFEBOOKS_FEEDBACK_EMAIL_TIMEOUT_SECONDS",
    "10",
)
SAFEBOOKS_FEEDBACK_RATE_LIMIT_COUNT = _env_int(
    "SAFEBOOKS_FEEDBACK_RATE_LIMIT_COUNT",
    "5",
)
SAFEBOOKS_FEEDBACK_RATE_LIMIT_WINDOW_SECONDS = _env_int(
    "SAFEBOOKS_FEEDBACK_RATE_LIMIT_WINDOW_SECONDS",
    str(10 * 60),
)

# Google OAuth sign-in. Keep real credentials in .env or deployment secrets.
SAFEBOOKS_GOOGLE_OAUTH_CLIENT_ID = _first_env("SAFEBOOKS_GOOGLE_OAUTH_CLIENT_ID", "GOOGLE_OAUTH_CLIENT_ID", default="")
SAFEBOOKS_GOOGLE_OAUTH_CLIENT_SECRET = _first_env("SAFEBOOKS_GOOGLE_OAUTH_CLIENT_SECRET", "GOOGLE_OAUTH_CLIENT_SECRET", default="")
SAFEBOOKS_GOOGLE_OAUTH_REDIRECT_URI = _first_env("SAFEBOOKS_GOOGLE_OAUTH_REDIRECT_URI", "GOOGLE_OAUTH_REDIRECT_URI", default="")

# Session security. Admin sessions have a shorter explicit policy than the
# general Django session and are also checked for inactivity in the admin
# authentication boundary.
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = _env_bool("SAFEBOOKS_SESSION_COOKIE_SECURE", "0")
CSRF_COOKIE_SECURE = _env_bool("SAFEBOOKS_CSRF_COOKIE_SECURE", "0")
SAFEBOOKS_ADMIN_SESSION_MAX_AGE_SECONDS = _env_int(
    "SAFEBOOKS_ADMIN_SESSION_MAX_AGE_SECONDS",
    str(8 * 60 * 60),
)
SAFEBOOKS_ADMIN_SESSION_IDLE_TIMEOUT_SECONDS = _env_int(
    "SAFEBOOKS_ADMIN_SESSION_IDLE_TIMEOUT_SECONDS",
    str(30 * 60),
)
SAFEBOOKS_ADMIN_TWO_FACTOR_PENDING_TIMEOUT_SECONDS = _env_int(
    "SAFEBOOKS_ADMIN_TWO_FACTOR_PENDING_TIMEOUT_SECONDS",
    str(5 * 60),
)
SAFEBOOKS_ADMIN_TWO_FACTOR_LOGIN_TIMEOUT_SECONDS = _env_int(
    "SAFEBOOKS_ADMIN_TWO_FACTOR_LOGIN_TIMEOUT_SECONDS",
    str(5 * 60),
)
SAFEBOOKS_ADMIN_TWO_FACTOR_LOGIN_MAX_ATTEMPTS = _env_int(
    "SAFEBOOKS_ADMIN_TWO_FACTOR_LOGIN_MAX_ATTEMPTS",
    "5",
)
SAFEBOOKS_ADMIN_TWO_FACTOR_LOGIN_LOCKOUT_SECONDS = _env_int(
    "SAFEBOOKS_ADMIN_TWO_FACTOR_LOGIN_LOCKOUT_SECONDS",
    str(5 * 60),
)
